- name: My sample CI/CD playbook
  hosts: ci-runner-1, ci-runner-2
  tasks:
   - name: build project
     ansible.builtin.command: npm ci --ignore-scripts
   - name: check lint
     ansible.builtin.command: npm run lint
   - name: run test
     ansible.builtin.command: npm test
