- name: My sample CI/CD playbook
  hosts: ci-runner-1, ci-runner-2
  tasks:
   - name: build project
     ansible.builtin.ping:
   - name: check lint
     ansible.builtin.debug:
       msg: Hello world
   - name: run test
     ansible.builtin.debug:
       msg: Hello worldans
