- name: My sample CI/CD playbook
  hosts: 192.168.56.8
  tasks:
   - name: build project
     ansible.builtin.command: npm ci --ignore-scripts
   - name: check lint
     ansible.builtin.command: npm run lint
   - name: run test
     ansible.builtin.command: npm test
